### ISSUE TITLE
是否可以增强page页面的excerpt字段功能

### ISSUE THREAD

**Issue by Pikaconan** [AlanDecode/Maverick#11]
想要使用 MetingJS 做一个音乐页面，因为 MetingJS 提供了 CDN 引入，可以直接在 head 标签里引入。

所以 page 的 excerpt 字段是否可以直接解析到 head 里，如：

```
excerpt: <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
<script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js"></script>
```

然后正文里：

```
<meting-js server="netease" type="playlist" id="#">
```

目前我是直接在正文里插入以上两段代码，播放器加载是稍慢的，不是很优雅==

**Comment by AlanDecode** [comment]
不行，这不是 excerpt 的作用。

**Comment by Pikaconan** [comment]
> 不行，这不是 excerpt 的作用。

emmm，只能期待插件系统了吗？通过 excerpt 是我异想天开了。

**Comment by AlanDecode** [comment]
可以在 config 文件中通过 `head_addon` 选项引入 CSS 和 JS 啊。

**Comment by Pikaconan** [comment]
> 可以在 config 文件中通过 `head_addon` 选项引入 CSS 和 JS 啊。

我想过这种方法，但是没去试，担心拖累整站的速度，刚才仔细去看了下文件似乎不是很大==谢谢
