### ISSUE TITLE
HTML Block 内部的 Markdown 格式无法被显示

### ISSUE THREAD

**Issue by derbalkon** [AlanDecode/Maverick#18]
举例如下：

### 如果写下面这种嵌套：
<img width="385" alt="截屏2020-04-12 上午12 40 33" src="https://user-images.githubusercontent.com/16346935/79049511-ad046700-7c56-11ea-9006-74490cd5adf5.png">

### 直接从 GitHub 上 Preview 这段文字，内部的 Markdown 格式会正确显示：
<img width="315" alt="截屏2020-04-12 上午12 40 48" src="https://user-images.githubusercontent.com/16346935/79049507-a970e000-7c56-11ea-8ba3-0f555783358a.png">

### 但是生成的网页上看起来会是这样：
<img width="265" alt="截屏2020-04-12 上午12 40 59" src="https://user-images.githubusercontent.com/16346935/79049497-a249d200-7c56-11ea-9261-922c1a440b16.png">

### 从生成的 html 里看，其内部的 Markdown 没有被正确地表达：
<img width="412" alt="截屏2020-04-12 上午12 51 37" src="https://user-images.githubusercontent.com/16346935/79049715-d96cb300-7c57-11ea-8f5e-785690502dfb.png">

更换了几个主题，发现最终生成的效果都是一样，应该和主题没什么关系。

**Comment by AlanDecode** [comment]
Maverick 使用 mistune 作为 Markdown 解析器，这个解析器可能对嵌套语法支持不佳。

**Comment by AlanDecode** [comment]
我在 4328bda24bf 中添加了一个语法：

```
[details][/details]
```

例如：

```
[details]
<summary>简介</summary>
`内容`
[/details]
```

应该可以暂时解决这个问题。
