### ISSUE TITLE
Is there any plan on supporting Notion as data source

### ISSUE THREAD

**Issue by ghost** [AlanDecode/Maverick#2]
Is there any plan on supporting Notion as data source  like https://github.com/mayneyao/gine-blog

**Comment by AlanDecode** [comment]
It seems like an interesting idea, but I haven't look into Notion API so much, so I can't say for sure. Currently I'd rather stay on using Markdown files as data source.

**Comment by ghost** [comment]
thank you  ! have a good nice day
