### ISSUE TITLE
请问如何升级Valine版本

### ISSUE THREAD

**Issue by Pikaconan** [AlanDecode/Maverick#21]
本来不是个问题，哪个版本都能用，无奈Leancloud华东节点的域名`https://tab.avoscloud.com`停止支持了，证书过期导致Valine评论异常（偶尔加载不出，或者左上角显示不安全）。
Valine作者表示下个版本修复（https://github.com/xCss/Valine/issues/320）
翻了下Valine文档没找到如何升级的描述，所以来这边问一下。

**Comment by Wittoy** [comment]
自行设置 [serverURLs](https://valine.js.org/configuration.html#serverURLs)

**Comment by Pikaconan** [comment]
> 自行设置 [serverURLs](https://valine.js.org/configuration.html#serverURLs)

搞定了，感谢！
