### ISSUE TITLE
每次推送到gh分支之后，自定义域名都会失效

### ISSUE THREAD

**Issue by matr1x-code** [AlanDecode/Maverick#22]
**Actual behavior**
每次在本地build之后，推送到master，然后调用action构建，再自动推送到gh分支之后，自定义域名都会失效，不知道如何解决？

**Expected behavior**

**How to reproduce**

**Environment and configuration**

* Python Version: 
* pip Version: 

**Error log**

**Additional information**

**Comment by AlanDecode** [comment]
在源目录下创建一个 static 文件夹，里面放 CNAME 文件，例如我的 Wiki 站：https://github.com/AlanDecode/site-Wiki

**Comment by matr1x-code** [comment]
好的谢谢，解决了
