### ISSUE TITLE
页面目录不能正常跳转

### ISSUE THREAD

**Issue by coco-hkk** [AlanDecode/Maverick#23]
md生成的目录可以在github上面正常显示和跳转，但网页上不能正常跳转。

目录的HTML
`<a href="#css">CSS</a>`

对应的小节标题的HTML
`<h2>CSS</h2>`

`<h2>CSS</h2>`没有设置id，所以目录不能正常跳转。

该怎么写md或设置？

谢谢

**Comment by AlanDecode** [comment]
Markdown 解析器不会自动加上 id，如果需要使用目录，请使用带有目录功能的主题；或者 h 标签也自己添加 id。
