### ISSUE TITLE
生成静态文件错误

### ISSUE THREAD

**Issue by GuoRan18** [AlanDecode/Maverick#25]
➜  Maverick git:(master) ✗ python ./build.py
Traceback (most recent call last):
  File "./build.py", line 9, in <module>
    from Maverick.Utils import print_color, Color
  File "/root/RemoteWorking/Maverick/Maverick/Utils.py", line 28
    def print_color(text: str, fg: Color = Color.BLACK.value, end='\n'):
                        ^
SyntaxError: invalid syntax

**Comment by AlanDecode** [comment]
什么环境？Python什么版本？

**Comment by GuoRan18** [comment]
Python3.8.5   
pip: 20.0.3

**Comment by AlanDecode** [comment]
这个环境我这边没有问题，请再次确认你的运行环境和Python，或者提供更多错误信息。

**Comment by Febuxostat-Pwn4** [comment]
这个兄弟，你的Python版本是2.x，你用命令的时候得用Python3来运行
