### ISSUE TITLE
我希望用vimwiki来组织

### ISSUE THREAD

**Issue by hantaotaohan** [AlanDecode/Maverick#27]
**Problem description**

**Environment and configuration**

* Python Version: 
* pip Version: 

**Additional information**
我希望用vimwiki来组织 但是我发现,Maverick所生成的链接都是"**/blog/archives/**"的 但vimwiki的语法都是绝对路径,所以无法用于vimwiki所以我希望支持vimwiki的链接格式

**Comment by AlanDecode** [comment]
目前还不支持自定义路径风格，但以后或许会支持
