### ISSUE TITLE
请问可以自定主题吗？

### ISSUE THREAD

**Issue by fly-potato-100** [AlanDecode/Maverick#3]
正在fork示例并跟随学习中

有看到template有个default的主题，想问下大佬有办法自订或者引用github pages里面的主题吗？

Thanks for reading

**Comment by AlanDecode** [comment]
可以更换主题，但是目前只有一款。
不能直接使用别的生成器主题。

**Comment by chena1982** [comment]
能把主题开放出来，让用户修改吗？

**Comment by AlanDecode** [comment]
本就是开放的啊。Templates 目录下的 Galileo 和 Kepler 是两个自带主题，你可以在此基础上修改。

第三方主题直接放在 Templates 目录下，然后在设置文件中修改 ​`template="主题名称"` 即可。

**Comment by AlanDecode** [comment]
https://github.com/AlanDecode/Maverick#Themes
