### ISSUE TITLE
sitemap.xml生成url路径问题

### ISSUE THREAD

**Issue by kaygb** [AlanDecode/Maverick#30]
您好，生成的sitemap文件内URL只包含页面路径不包含域名，不被google serach console识别

![image](https://user-images.githubusercontent.com/48642860/107119366-0d3d5700-68c2-11eb-9a8e-8967cb683e3c.png)

目前的生成格式如下：

~~~xml
<url>
<loc>/Maverick/about/</loc>  # 这里没有包含域名
<lastmod>2017-06-28</lastmod>
<changefreq>always</changefreq>
<priority>0.8</priority>
</url>
~~~

可能需要的格式为：

~~~xml
<url>
<loc>https://alandecode.github.io/Maverick/about/</loc>  # 这里包含了域名
<lastmod>2017-06-28</lastmod>
<changefreq>always</changefreq>
<priority>0.8</priority>
</url>
~~~

感谢您的辛苦付出，祝安好！

**Comment by AlanDecode** [comment]
若需要在 sitemap 中包含域名，请在配置文件中设置 `site_prefix` 选项，例如：

```
site_prefix = "https://domain.com/"
```

**Comment by kaygb** [comment]
> 若需要在 sitemap 中包含域名，请在配置文件中设置 `site_prefix` 选项，例如：
> 
> ```
> site_prefix = "https://domain.com/"
> ```

好的，感谢作者大大
