### ISSUE TITLE
是否可以使用Hexo的主题？

### ISSUE THREAD

**Issue by tfnick** [AlanDecode/Maverick#32]
**Problem description**
想知道，这个小工具是否可以直接使用Hexo的主题？

**Environment and configuration**

* Python Version: 
* pip Version: 

**Additional information**

**Comment by tfnick** [comment]
如果不行的话，只能去折腾hexo了

**Comment by sihuan** [comment]
这是一个博客生成器，和 hexo 是同类的应用，目前这个工具的主题和 hexo 主题并不兼容

**Comment by tfnick** [comment]
设计主题之初，兼容主流的主题，比如Hexo是否可行呢

**Comment by AlanDecode** [comment]
Hexo是基于NodeJS的框架，Maverick是基于Python的，因此不太可能
