### ISSUE TITLE
执行这一步没反应，没有生成dist文件夹。python3 mvrk.py --config ./demo_src/config.py --source_dir ./demo_src/ --build_dir ./dist/

### ISSUE THREAD

**Issue by HelIwalker** [AlanDecode/Maverick#37]
我是在D:\project\GitHub\Maverick下直接Git Bash here执行的

**Comment by Adkimsm** [comment]
你系统如果是win10或win8的话，可以尝试将命令中 ’python3’ 替换为 ’python’ 或 ‘py’。我在运行这个命令时遇到了和你一样的问题，用此方法即解决。

**Comment by HelIwalker** [comment]
> 你系统如果是win10或win8的话，可以尝试将命令中 ’python3’ 替换为 ’python’ 或 ‘py’。我在运行这个命令时遇到了和你一样的问题，用此方法即解决。

非常感谢

**Comment by Adkimsm** [comment]
记得把此 Issue Close。
