### ISSUE TITLE
请问有支持TOC的主题了吗？

### ISSUE THREAD

**Issue by wzywalker** [AlanDecode/Maverick#40]
本来就是因为简书没有TOC就想搬家，然后干脆做独立博客算了，了解到Maverick很酷的资源加载方式就用在了这个项目上，结果发现主题不支持TOC，我另一个博客用hexo搭建的，发现里面大部分主题是有TOC的，会否继续支持？

**Comment by walkerwzy** [comment]
原来开普勒那个主题有TOC，赞

**Comment by wzywalker** [comment]
原来开普勒那个主题有TOC，赞。就是能美化下就更好了
