### ISSUE TITLE
RSS 的兼容性问题

### ISSUE THREAD

**Issue by Pikaconan** [AlanDecode/Maverick#7]
**Problem description**
1. <link>标签中只有 /，无法解析出原文链接
2. 文章内图片无法显示
以上问题只存在 iOS 平台的 RSS Reader Prime 中，是一个本地阅读器。在 Feedly 中以上问题会被自动优化。
[![l2Nr0s.md.png](https://s2.ax1x.com/2020/01/08/l2Nr0s.md.png)](https://imgchr.com/i/l2Nr0s)

**Environment and configuration**
iOS 平台的 RSS Reader Prime

* Python Version: 3.7
* pip Version: 

我的conf.py： https://github.com/luhexyz/site-Blog/blob/master/conf.py
测试过我自己和您的 RSS 链接，以上问题依然存在。
（唯一的区别在于我的头像无法显示，您的头像可以显示，应该是因为我没开 jsdelivr 的缘故）

**Additional information**
我的图片是使用图床链接插入的，没有配置过 fetch_remote_imgs

**Comment by AlanDecode** [comment]
1. 大多数 RSS 阅读器可以处理这种只有 path 的链接，例如 inoreader 就没问题
2. 要显示完整链接，在设置中调整 `site_prefix` 为完整前缀，例如 `https://xxx.com/`

**Comment by Pikaconan** [comment]
感谢！在修改 site_prefix 字段为 https://xxx.com/ 之后，头像和原文链接都已正常。
图片依旧无法加载，并且我注意到带有图片的文章，在 RSS Reader Prime 上字体会变成小一号的宋体，而纯文字的文章不受影响。
在仔细对比现在的 xml 文件和之前 VOID 主题的 xml 文件后发现：
- 前者将文章全部内容放置在 description 标签内；
- 而后者的 description 标签内是自动生成的摘要，随后 content 标签放置文章原文。

**Comment by Pikaconan** [comment]
修改 site_prefix 字段为 https://xxx.com/ 之后，valine 的阅读量计数出现了问题，我注意到您已经在主题中修复了。
但是我这边 pull 却提示没有更新，是否与子模块@后面的代码相关，代码不同就无法 pull 到更新。初步使用搜索引擎没有找到答案，如若是个过于基础的 git 知识，请忽略这条。
（我已使用 git 方式引入了主题使 valine 计数生效。）

**Comment by AlanDecode** [comment]
> 图片依旧无法加载

懒加载的原因，后面可能会去掉。

> 对比现在的 xml 文件和之前 VOID 主题的 xml 文件后发现

RSS 协议不同而已。

> 我这边 pull 却提示没有更新

需要更新 submodule。如果你用的是 Linux 或者 Mac，我的仓库里有一个 Makefile，使用 `make theme` 更新主题。更新 Maverick 则是 `make mvrk`。

**Comment by Pikaconan** [comment]
>懒加载的原因，后面可能会去掉。

我看到懒加载已经移除，重新订阅 RSS 后，图片可以正常加载，一切都已完美。感谢！
之前在用 VOID 时，开与不开懒加载观感很不一样；现在 Maverick 不开懒加载感受不是那么明显。事实上有一个促使我换到 Maverick 的原因就是加载图片比 VOID 快很多。可能这就是静态的优势吧。

>需要更新 submodule。如果你用的是 Linux 或者 Mac...

（尴尬，之前没有去看 Makefile 里写了什么）使用 Makefile 文件中的命令做成三个 bat 后：
![lWMzWQ.png](https://s2.ax1x.com/2020/01/09/lWMzWQ.png)
单独使用 update_maverick.bat 无法 push，看到作者在[完全使用 GitHub 写博客](https://blog.imalan.cn/archives/blog-with-github/)中提到：
![lWKcE8.png](https://s2.ax1x.com/2020/01/09/lWKcE8.png)
即在 git add . 之前需要 cd ..，才能 push。
因为我通过使用 update_maverick.bat 和 update_site.bat，已经更新到最新版本，所以无法验证这样是否可行。如果我说的正确，请关闭此 issue，我的疑问已全部消除。
再次感谢您的帮助！

**Comment by AlanDecode** [comment]
使用 Makefile 不需要 `cd ..`，因为每条指令都在原来的工作目录中。bat 则需要切换回去。
