### ISSUE TITLE
运行会报错

### ISSUE THREAD

**Issue by qianmianyao** [AlanDecode/Maverick#9]
```

Site prefix: /
Source dir: /root/app/Maverick/test_src/
Build dir: ./test_dist/
Start clean...done.
Loading contents...
Traceback (most recent call last):
  File "build.py", line 43, in <module>
    main(sys.argv[1:])
  File "build.py", line 39, in main
    builder.build_all()
  File "/root/app/Maverick/Maverick/Builder.py", line 142, in build_all
    content = Content(content_path)
  File "/root/app/Maverick/Maverick/Content.py", line 33, in __init__
    self.meta = Metadata(yaml.safe_load(m.group(1)))
  File "/root/app/Maverick/Maverick/Metadata.py", line 17, in __init__
    self["date"] = moment.date(str(fr.get("date", ""))).locale(g_conf.locale)
  File "/usr/local/lib/python3.6/site-packages/moment/core.py", line 67, in locale
    self._date = pytz.timezone(zone).normalize(self._date)
  File "/usr/local/lib/python3.6/site-packages/pytz/tzinfo.py", line 252, in normalize
    offset = dt.tzinfo._utcoffset
AttributeError: 'StaticTzInfo' object has no attribute '_utcoffset'

```

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by AlanDecode** [comment]
检查文章日期格式，或者Python版本（至少3.5）

**Comment by qianmianyao** [comment]
![8C303B91-7B3D-4111-B95E-76A85ADE5EF6](https://user-images.githubusercontent.com/32097980/73519782-efcae700-443c-11ea-8a8d-836b00553857.png)

为啥会css丢失

**Comment by qianmianyao** [comment]
caddy作为web服务器
http://193.112.128.133:2015/

**Comment by AlanDecode** [comment]
config.py 里：

​```
enable_jsdelivr = {
    "enabled": False,
    "repo": ""
}
​```

**Comment by qianmianyao** [comment]
![45B9C5CC-3489-4155-846C-B9E5A41B7244](https://user-images.githubusercontent.com/32097980/73528525-02025080-4450-11ea-834a-6f3bee46416b.jpeg)
这样对吗，但是404了

**Comment by qianmianyao** [comment]
好啦

**Comment by qianmianyao** [comment]
请问可以设置中文吗

**Comment by AlanDecode** [comment]
https://github.com/AlanDecode/Maverick/blob/master/README.md#options-for-your-site

**Comment by qianmianyao** [comment]
![068CE406-18BF-47ED-B082-849BDB2659A5](https://user-images.githubusercontent.com/32097980/73548014-098b1f00-447b-11ea-945d-b72d18970878.jpeg)
是这个参数吗，没有示例，不知道怎么改，改了没用呀

**Comment by AlanDecode** [comment]
这个要看主题如何提供的，Galileo主题和Kepler主题的中文选项都是 zh-CN
